# Generated by Django 5.1.3 on 2024-11-26 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_rename_content_post_comment_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='comment',
        ),
    ]
